codecov:
  require_ci_to_pass: yes
  precision: 2
  round: down
  layout: "reach,diff,flags,tree"
  behavior: default

coverage:
  precision: 2
  round: down
  range:
    - 70.0
    - 100.0

ignore:
  - "node_modules"
  - "test"
  - "dist"
  - "build"

flags:
  unittests:
    carryforward: yes

comment:
  layout: "reach, diff, flags, tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  paths:
    - "contracts"
    - "src"

github:
  checks:
    annotations: yes

status:
  project:
    default:
      threshold: null
      base: null
  patch:
    default:
      threshold: null
  changes:
    default:
      threshold: null
